### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException 	at Main.main(Main.java:11)

### ISSUE THREAD

**Issue by SodeshDindayal** [yejianfengblue/so62749048#1]
There seems to be a problem with this line:
public static void main(String[] args) throws IOException, JAXBException 

Which basically tells me that there's some variable with a null value, but I can't seem to find what variable has it

**Comment by yejianfengblue** [comment]
Did you build this project by maven successfully? The NullPointerException complains the file doesn't exist. Check the directory `/target/classes`. Is there a file named `items.xml`?

**Comment by yejianfengblue** [comment]
My code puts the file `items.xml` under `/src/main/resources`, so after maven compile, the file should be copied under `/target/classes`, which is the so-called classpath. 

This line of code read the file `items.xml` from classpath.
```java
File file = new File(Main.class.getResource("items.xml").getFile());
```
You can change this line of code to your original
```java
File file = new File("items.xml")
```

**Comment by SodeshDindayal** [comment]
Changing the line back to the original works, thank you

**Comment by SodeshDindayal** [comment]
I have a question, when I unmarshall the file, is the data being stored? Or is it just being displayed? 
If its the latter, how would I go about storing the data to then make changes to it without making changes to the xml file itself?

**Comment by yejianfengblue** [comment]
After unmarshall the file, that is, after this line fo code
```java
Items itemData = (Items) un.unmarshal(file);
```
The data is stored in the your variable `itemData`, that is, in your computer memory (RAM).

You call to `System.out.println()` prints the `itemData` to console, that is, just being displayed. After that, your program terminates and your data in memory is gone.

If you want to change data and store to somewhere after your program terminates, consider [store (serialize) to file](https://www.baeldung.com/java-serialization), or store to database.

One example of database is [MySQL](https://www.mysql.com/). Some tutorial is [here](https://www.baeldung.com/java-connect-mysql). The database topic is much complicated than unmarshalling XML.
